name: Deploy & Trigger E2E Test

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    steps:
      # -----------------------
      # Checkout source code
      # -----------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # -----------------------
      # Fake deploy step
      # (thực tế thay bằng helm / terraform / ansible / ssh / kubectl)
      # -----------------------
      - name: Deploy application to QA
        run: |
          echo "🚀 Deploy application to QA environment"
          echo "Deploy success!"

      # -----------------------
      # Trigger Playwright E2E (repo testcase)
      # -----------------------
      - name: Trigger Playwright tests (testcase repo)
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TEST_REPO_TOKEN }}" \
            https://api.github.com/repos/thinhnh96/demoapp/dispatches \
            -d '{
              "event_type": "run-e2e",
              "client_payload": {
                "env": "qa",
                "tag": "@smoke",
                "base_url": "https://www.saucedemo.com"
              }
            }'
